### ISSUE TITLE
Support for RGB176 devices

### ISSUE THREAD

**Issue by hearttheart** [keefo/NeewerLite#10]
Hi, this is awesome! Do you think you could add support for Neewers RGB176 devices?

https://www.amazon.ca/Dimmable-3200K-5600K-Camcorder-Lighting-Included/dp/B08JFXJNXL/

Would be great!

**Comment by keefo** [comment]
I have placed an order for this light. Will integrate after I get it.

**Comment by keefo** [comment]
Add the support of this light and tested.
<img width="692" alt="Screen Shot 2022-02-21 at 9 12 25 PM" src="https://user-images.githubusercontent.com/809588/155067223-d0f26d99-d803-473f-a05f-3c8abc4a0d73.png">

**Comment by keefo** [comment]
No logic change, I only need to add the image of this light and doing a bit of testing.

https://github.com/keefo/NeewerLite/commit/a3cb1cc458925234abfaaee14acc127b33cd4db2
