### ISSUE TITLE
Neewer RGB176

### ISSUE THREAD

**Issue by markhellier** [keefo/NeewerLite#15]
Hi, I have a These panels and they were not being found on my Mac Studio running Monterey.
I'm not a programmer, but used a BLE explorer and found that the Peripheral name of mine was "NEE" . downloaded Xcode and added this to isValidPeripheralNameand I was back in business. Not sure if that helps.

maybe newer Lights have a different name?

**Comment by menant** [comment]
A little different but still related to this light:

I am able to see the RGB176 appear in NeewerLite after I first establish connectivity with it using the iOS Neewer app running on my Mac M1 and then close the app. I can then control the light using NeewerLite.

**Issue**: when I switch the light off using NeewerLite, after a timeout period, the RGB176 disappears from the app. It seems that the light might not be receiving a keep-alive message or similar.

**Comment by irwando** [comment]
Same issue here.

**Comment by menant** [comment]
> A little different but still related to this light:
> 
> I am able to see the RGB176 appear in NeewerLite after I first establish connectivity with it using the iOS Neewer app running on my Mac M1 and then close the app. I can then control the light using NeewerLite.
> 
> **Issue**: when I switch the light off using NeewerLite, after a timeout period, the RGB176 disappears from the app. It seems that the light might not be receiving a keep-alive message or similar.

Just tried with version 0.9.
The RGB176 still disappears from NeewerLite some minutes after I switch it off.

I am still wondering if there's a way to have a keepalive work for this.

Is there anything I can do to help with troubleshooting?

**Comment by keefo** [comment]
Hi @menant 
I have a sendKeepAlive function sending a [command](https://github.com/keefo/NeewerLite/blob/main/NeewerLite/NeewerLite/Model/NeewerLight.swift#L351) every 10s. It seems the light still want to turn off the BLE broadcasting.  

If you use iOS app connect the light and switch the light off. Do you see the light icon in the app still active!?

**Comment by menant** [comment]
I use the iOS app on the same Mac with Apple silicon that runs NeewerLite app.

It seems that the RGB176 "goes to sleep" after 5 minutes, and the on/off switch disappears from the interface (see screenshots). I have to turn the light back on manually, and click the light in the iOs app for it to reconnect.

When the lights are off (within first 5 minutes):
<img width="487" alt="Screenshot 2023-02-22 at 9 41 37 PM" src="https://user-images.githubusercontent.com/10995501/220829386-8afe2e9d-d021-46cf-ad29-b73ec5119cb8.png">

RGB176 disappears after 5 minutes:
<img width="487" alt="Screenshot 2023-02-22 at 9 41 14 PM" src="https://user-images.githubusercontent.com/10995501/220829405-12272a82-c69b-43c0-88cf-8aa4ae569ee1.png">

**Comment by keefo** [comment]
Fixed in v1.1
