### ISSUE TITLE
Support for the Neewer GL1 Key Light

### ISSUE THREAD

**Issue by menant** [keefo/NeewerLite#17]
**Any chance to add full support for the GL1 Key Light?**
[product page](https://neewer.com/products/neewer-15-5-45w-gl1-gaming-key-light-66600553)

As of now, I can discover the light and switch it on/off, but moving the BRR and CCT sliders switches the light off and it cannot be toggled again unless I close NeewerLite, reconfigure the light with the official macOS app (Neewer Live) and close it, then restart NeewerLite.

**Comment by keefo** [comment]
Do you see any crash report from bluetoothd in the /Library/Logs/DiagnosticReports folder?

**Comment by menant** [comment]
Thanks for your follow-up.
No files with anything related to BlueTooth in that directory.

**Comment by keefo** [comment]
Please check to see if the v0.9 works.

**Comment by menant** [comment]
Sorry: same problem with version 0.9.

Once I touch any of the sliders, the light goes off and I cannot interact with the light anymore, even if I kill and restart the app. I can only get the light to register with NeewerLite after I re-attaach that light to my Mac using the official "Neewer Live" app.

**Comment by ryanmccool** [comment]
Just noting that the same happens on my system.

**Comment by keefo** [comment]
v1.1 add support for this light
