### ISSUE TITLE
NEEWER RGB CB60

### ISSUE THREAD

**Issue by yankijp** [keefo/NeewerLite#19]
NEEWER RGB CB60 does not work with this. It seems like something has changed as in order for the phone app to see the light, you need to go to a new section called "Infinity" to add the device. My multiple 660 rgb work correctly. 

I can still manually pair to the light via bluetooth so it is still a bluetooth device.

**Comment by yankijp** [comment]
I managed to get it working. Looked at an issue someone else put. The device name prefix was "nw-" so I changed Neewer to that in the code. It took several tries to link correctly (I held the cct button on the light to reset the bluetooth) and it was able to get a link. I can control the light correctly now.

**Comment by keefo** [comment]
please test v0.9 to see if it works.

**Comment by keefo** [comment]
v1.0 has been released, it supports CB60 RGB with 17 FX scenes.
