### ISSUE TITLE
Support for Loupedeck? Code for Scene Switching?

### ISSUE THREAD

**Issue by montaemontana** [keefo/NeewerLite#20]
I would like create a macro sequence on my Loupedeck Live allowing me to toggle on the Squad Car scene (on one of my lights) as well as a siren from my soundboard on the first push. On the second push it would then toggle off the scene and sound, returning the light to the pervious setting. Is this currently possible? This is my first time attempting to use code in my workflow so I really don't know the first thing about any of this. Thank you in advance.

**Comment by keefo** [comment]
v0.9 should support your task.

**Comment by montaemontana** [comment]
Thank you so much!
