### ISSUE TITLE
Scenes on NEEWER RGB168

### ISSUE THREAD

**Issue by ericvicenti** [keefo/NeewerLite#23]
Hi, thanks for the project!

Everything works for me except the scenes on the RGB168 are not working at all, probably because it supports 17 scenes rather than then 9 original ones

https://www.bhphotovideo.com/c/product/1733871-REG/neewer_66600603_rgb168_18_3_led_panel.html

**Comment by keefo** [comment]
Please try to extend the scene number here to 10, 11, ..., 16, 17 and see if it works for your light. If it does, please let me know. 

https://github.com/keefo/NeewerLite/blob/main/NeewerLite/NeewerLite/Model/Command.swift#L107

**Comment by keefo** [comment]
Fix this in version 1.1

<img width="536" alt="Screenshot 2023-11-10 at 3 58 35 PM" src="https://github.com/keefo/NeewerLite/assets/809588/1da47e9d-4140-4eb6-a850-e2ea73fdd801">

**Comment by keefo** [comment]
v 1.1 support 17 fx now.
