### ISSUE TITLE
using with SNL530

### ISSUE THREAD

**Issue by infocurieux** [keefo/NeewerLite#25]
I try to use NEEWERLITE with NEEWER-SNL530 (name displayed on Bluetooth inspector), on/off is working but not brightness or CCT

I try to add SNL530 in the NeewerLight file but I have some Error while the build (I am a very Newbies in coding

**Comment by liquidvisual** [comment]
I wasn't able to get this to compile with XCode 15 - there's too many deprecations it seems. Does anyone else know their way around Swift?

**Comment by keefo** [comment]
I compile it under xcode Version 15.0.1 (15A507) last night, I don't see deprecations message.
