### ISSUE TITLE
Trying to figure out why the NeewerLite app on this site refuses to find the bluetooth connection for the lights?

### ISSUE THREAD

**Issue by inbashkir** [keefo/NeewerLite#28]
Ive tried everything from the bluetooth logo being solid, and having it blinking. Nothing is helping my find the lights in the software or I my Mac settings.

Can anyone assist? 

Regards

Neewer 660RGB

**Comment by keefo** [comment]
First, make sure your Neewer LED light has bluetooth logo blinking.  Blinking means it is in waiting for pair mode. AFAIK, the Neewer light can only have with 1 bluetooth connection.  If you connect you light to you phone app, the bluetooth logo on the light will be solid, at this point, the NeewerLite app can not find and pair it.

While it is blinking, are you be able to connect it in your phone app? If not, then it might be a hardware issue in your light.

If you can connect it in your phone app, then discount it and make the logo blinking again.

Now, go to your mac and use a bluetooth scan app to check for your light signal.  AS long as you can see its name in the scan list. 

Please post your light bluetooth name and light model in here.

**Comment by inbashkir** [comment]
I’ve got it working. Thank you!Sent from my iPhoneOn Oct 24, 2023, at 2:24 PM, Xu Lian ***@***.***> wrote:﻿
First, make sure your Neewer LED light has bluetooth logo blinking.  Blinking means it is in waiting for pair mode. AFAIK, the Neewer light can only have with 1 bluetooth connection.  If you connect you light to you phone app, the bluetooth logo on the light will be solid, at this point, the NeewerLite app can not find and pair it.
While it is blinking, are you be able to connect it in your phone app? If not, then it might be a hardware issue in your light.
If you can connect it in your phone app, then discount it and make the logo blinking again.
Now, go to your mac and use a bluetooth scan app to check for your light signal.  AS long as you can see its name in the scan list.
Please post your light bluetooth name and light model in here.
