### ISSUE TITLE
Please add "NW-20200015&6C9E0100"

### ISSUE THREAD

**Issue by liquidvisual** [keefo/NeewerLite#29]
I tried to add this myself adding `peripheralName.starts(with: "NW-")` on **line:263** in Model/NeewerLight.swift but nothing will compile under XCode 15 due to deprecations. Can anyone please help?

Btw, this is for the RGB1 Magentic Handheld Light Stick: 
https://neewer.com/products/neewer-cri98-rgb1-handheld-led-video-light-66601508

**Comment by keefo** [comment]
I have ordered this light, will test it ASAP.

**Comment by liquidvisual** [comment]
Thanks Keefo! Did you have any luck?

**Comment by keefo** [comment]
> Thanks Keefo! Did you have any luck?

https://youtube.com/shorts/WZH3NwzGGyo

**Comment by keefo** [comment]
v1.1 added support of this light.

**Comment by TheMitchingHour** [comment]
@keefo, you're such a legend! It works great, thank you!!!

**Comment by liquidvisual** [comment]
@keefo, you're such a legend! It works great, thank you!!!
