### ISSUE TITLE
1.0 doesn't show controls

### ISSUE THREAD

**Issue by ttyS0** [keefo/NeewerLite#32]
The 1.0 version shows my RGB176 A1 after a scan, but the controls for turning it on, etc, don't display. The 0.9 version works fine, though. 

I'm on Sonoma 14.1.1 on a Mac Studio.

**Comment by keefo** [comment]
There is UI change regarding how light is managed. On the toolbar, if you click the control view. You should see new control panels.

By default, you are in lights Library and Scan view.

![Screenshot_11_10_23__2_44 PM-2](https://github.com/keefo/NeewerLite/assets/809588/4d400a9e-e884-4ccd-8b71-89271b818cdf)

**Comment by keefo** [comment]
This is how 'Control Panel' looks like.

<img width="791" alt="Screenshot 2023-11-10 at 2 46 18 PM" src="https://github.com/keefo/NeewerLite/assets/809588/b191a871-fbab-468a-8800-c89f79c55556">

**Comment by ttyS0** [comment]
Ohhhhh! Didn't even notice that. Thanks for the help, and sorry for the noise. 

On a side note, I've super appreciative for this application.
