### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by fribse** [keefo/NeewerLite#4]
Wow, this looks very interesting, unfortunately I'm not on mac. Have you tried creating a docker for it? I guess it would just require a bluetooth dongle, and then it should run in 'swift' containre?

**Comment by keefo** [comment]
It reply on [Core Bluetooth framework](https://developer.apple.com/documentation/corebluetooth), as long you could run macOS in your docker. It should work.  

https://github.com/sickcodes/Docker-OSX

**Comment by fribse** [comment]
Hi @keefo 
I see, that would be a way, but that requires a display as I understand it, which is a nogo, it needs to be headless, but thankyou for the pointer!
