### ISSUE TITLE
setLightHSI isn't working for me

### ISSUE THREAD

**Issue by TheMitchingHour** [keefo/NeewerLite#53]
This is my light:

<img width="491" alt="Screenshot of NeewerLite (7-1-2024, 10-07-59 am)" src="https://github.com/keefo/NeewerLite/assets/86508145/1134fb54-5872-4e63-8cfe-70efcbd779f2">

I'm trying to change it from pink to white via terminal, i've tried the following but neither work for me:

```
open "neewerlite://setLightHSI?light=Back_Wall&HUE=0&Saturation=0&Brightness=50"
```

```
open "neewerlite://setLightHSI?light=Back_Wall&RGB=ffffff&Saturation=0&Brightness=50"
```

Curiously, I noticed if I change the light tab from HSI to CCT in the app and then run the script, it _will_ switch back to HSI - but nothing else changes. Right now I'm only able to successfully toggle the on/off state of lights. Am I doing anything wrong?

**Comment by keefo** [comment]
Thanks for reporting. I will address this issue ASAP.

**Comment by TheMitchingHour** [comment]
Hi @keefo, hope you've been well. Sorry to bother you, was just wondering if you've had any luck solving this issue - or is it a limitation of the Neewer hardware? I'd be happy to throw some money on it if you can fix it.

**Comment by keefo** [comment]
Hi @TheMitchingHour 
I have ran HSI test on my RGB 176 light again. I haven't be able to reproduce the issue.
QQ, when you drag the color wheel in the HSI tab view. Did your light change color?

**Comment by TheMitchingHour** [comment]
Hi @keefo, thanks for replying. When I mouse drag the colour wheel in the HSI tab, the light changes colour perfectly. It's only when I run this terminal command targeting a specific named light _"Back_Wall"_ that nothing changes:

```
open "neewerlite://setLightHSI?light=Back_Wall&RGB=ffffff&Saturation=0&Brightness=50"
```

Do I have the correct syntax/format? If I switch to another tab view (CCT or FX etc), when I run the terminal command, the tab view switches back to HSI on that light (so it appears to be synched and working in some capacity), it's just not changing the colour as expected.

I don't have a RGB 176 model, but I have tested on the RGB660 and the RGB1-EFFE1B (stick light) and they both have the same result.

**Comment by keefo** [comment]
The command syntax/format is correct.
Please try version 1.6.1 to see if it works.

**Comment by TheMitchingHour** [comment]
Awesome, version 1.6.1 seemsed to do the trick. Everything working superb now - thank you!

**Comment by keefo** [comment]
Hi @TheMitchingHour, thank you for your support! I really appreciate it. ❤️
