### ISSUE TITLE
BH30-S Model found but no actions can be performed

### ISSUE THREAD

**Issue by romefort** [keefo/NeewerLite#55]
The app detects correctly my BH30-S RGB, I got access to the controls but none of them seems to work. Am I missing something?

**Comment by keefo** [comment]
I ordered this light. I will take a look once I have it.

**Comment by keefo** [comment]
Version 1.6 should support this light.
Here is a demo
https://youtu.be/BhPFeWTikdk

**Comment by romefort** [comment]
amazing, thank you so much!
