### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by jvlians** [keefo/NeewerLite#61]
Currently, there don’t seem to be any installation instructions for this project. Digging through the package, I can see several docs files, none of which indicate how to install this app. Further, I can see the xcodeproj in the package, and trying to manually compile it in terminal fails as I don’t have the key your “App Store team”.

How on earth are we meant to install this as an app? Can you update the documentation to better communicate this to users? The only relevant stuff I found online asks this exact question, with no answer.

**Comment by keefo** [comment]
Doc is updated

https://github.com/keefo/NeewerLite?tab=readme-ov-file#how-to-install-pre-build-app
