### ISSUE TITLE
Reading channel status/comment in NeewerLight.swift

### ISSUE THREAD

**Issue by ratmice** [keefo/NeewerLite#8]
There is a comment in NeewerLight

https://github.com/keefo/NeewerLite/blob/d8b6ea4eded4f15a48fc33afb5859b6638aa2212/NeewerLite/NeewerLite/Model/NeewerLight.swift#L446

Which I imagine happens when you send: 
> [0x78,0x84,0x00,0xFC]
https://github.com/keefo/NeewerLite/blob/main/NeewerLite/NeewerLite/Model/NeewerLight.swift#L44

I believe this represents the channel status and should contain a `0-8` at bytes[2],
I tried to document it below here: https://github.com/ratmice/neewerctl/blob/main/src/device.rs#L119-L123

**Comment by keefo** [comment]
I have released v0.7 which contain this feature.
